version: '3'

services:
  nestjs-app:
    container_name: nestjs_container
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db

  mysql-db:
    container_name: mysql_container
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: neoxdb
      MYSQL_USER: neoxuser
      MYSQL_PASSWORD: neoxpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: